# This is a sample build configuration for Maven.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Dockerhub as your build environment.
# image: maven:3.3.3
# testing if pipeline build works on commit - testing
image: tipotapp/tipo-build:latest

pipelines:
  branches:
    develop:
      - step:
          script: # Modify the commands below to build your repository.
                - export AWS_ACCESS_KEY_ID=$DEV_AWS_ACCESS_KEY_ID
                - export AWS_SECRET_ACCESS_KEY=$DEV_AWS_SECRET_ACCESS_KEY                
                - export S3_BUCKET=$dev_ui_s3_bucket
                - export google_client_id=$dev_google_client_id
                - export google_recaptcha_sitekey=$dev_google_recaptcha_sitekey
                - export cognito_client_id=$dev_cognito_client_id
                - export cognito_identity_pool_id=$dev_cognito_identity_pool_id
                - export cognito_region=$dev_cognito_region
                - export cognito_user_pool_id=$dev_cognito_user_pool_id
                - export TIPOAPP_S3_BUCKET_PUBLIC_DIR=$dev_tipoapp_public_directory_path
                - export TIPOAPP_S3_BUCKET_PRIVATE_DIR=$dev_tipoapp_private_directory_path
                - export TIPOAPPBASE_S3_BUCKET_PUBLIC_DIR=$dev_tipoappbase_public_directory_path
                - export TIPOAPPBASE_S3_BUCKET_PRIVATE_DIR=$dev_tipoappbase_private_directory_path
                - mvn --version
                - mvn -X clean deploy -Dall
    master:            
      - step:
          script: # Modify the commands below to build your repository.
                - export AWS_ACCESS_KEY_ID=$PROD_AWS_ACCESS_KEY_ID
                - export AWS_SECRET_ACCESS_KEY=$PROD_AWS_SECRET_ACCESS_KEY
                - export S3_BUCKET=$prod_ui_s3_bucket
                - export google_client_id=$prod_google_client_id
                - export google_recaptcha_sitekey=$prod_google_recaptcha_sitekey
                - export cognito_client_id=$prod_cognito_client_id
                - export cognito_identity_pool_id=$prod_cognito_identity_pool_id
                - export cognito_region=$prod_cognito_region
                - export cognito_user_pool_id=$prod_cognito_user_pool_id
                - mvn --version
                - mvn -X clean deploy -Dall