# This is a sample build configuration for Maven.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Dockerhub as your build environment.
# image: maven:3.3.3

image: tipotapp/tipo-build:latest

pipelines:
  branches:
    master:
      - step:
          script: # Modify the commands below to build your repository.
            - mvn --version
            - mvn -X clean deploy -Dall