# This is a sample build configuration for Maven.
# Only use spaces to indent your .yml configuration..
# -----
# You can specify a custom docker image from Dockerhub as your build environment.
# image: maven:3.3.3
# testing if pipeline build works on commit - testing
image: tipotapp/tipo-build:latest

pipelines:
  branches:
    develop:
      - step:
          script: # Modify the commands below to build your repository.
                - export USER_S3_BUCKET=$dev_user_s3_bucket
                - export AWS_ACCESS_KEY_ID=$DEV_AWS_ACCESS_KEY_ID
                - export AWS_SECRET_ACCESS_KEY=$DEV_AWS_SECRET_ACCESS_KEY                
                - export S3_BUCKET=$dev_ui_s3_bucket
                - export GOOGLE_CLIENT_ID=$dev_google_client_id
                - export GOOGLE_RECAPTCHA_SITEKEY=$dev_google_recaptcha_sitekey
                - export COGNITO_CLIENT_ID=$dev_cognito_client_id
                - export COGNITO_IDENTITY_POOL_ID=$dev_cognito_identity_pool_id
                - export COGNITO_REGION=$dev_cognito_region
                - export COGNITO_USER_POOL_ID=$dev_cognito_user_pool_id
                - mvn --version
                - mvn -X clean deploy -Dall
    master:            
      - step:
          script: # Modify the commands below to build your repository.
                - export USER_S3_BUCKET=$prod_user_s3_bucket
                - export AWS_ACCESS_KEY_ID=$PROD_AWS_ACCESS_KEY_ID
                - export AWS_SECRET_ACCESS_KEY=$PROD_AWS_SECRET_ACCESS_KEY
                - export S3_BUCKET=$prod_ui_s3_bucket
                - export GOOGLE_CLIENT_ID=$prod_google_client_id
                - export GOOGLE_RECAPTCHA_SITEKEY=$prod_google_recaptcha_sitekey
                - export COGNITO_CLIENT_ID=$prod_cognito_client_id
                - export COGNITO_IDENTITY_POOL_ID=$prod_cognito_identity_pool_id
                - export COGNITO_REGION=$prod_cognito_region
                - export COGNITO_USER_POOL_ID=$prod_cognito_user_pool_id
                - mvn --version
                - mvn -X clean deploy -Dall
