# This is a sample build configuration for Maven.
# Only use spaces to indent your .yml configuration..
# -----
# You can specify a custom docker image from Dockerhub as your build environment.
# image: maven:3.3.3
# testing if pipeline build works on commit - testing
image: tipotapp/tipo-build:latest

pipelines:
  branches:
    develop:
      - step:
          script: # Modify the commands below to build your repository.
                - export USER_S3_BUCKET=$dev_user_s3_bucket
                - export AWS_ACCESS_KEY_ID=$DEV_AWS_ACCESS_KEY_ID
                - export AWS_SECRET_ACCESS_KEY=$DEV_AWS_SECRET_ACCESS_KEY
                - export AWS_DEFAULT_REGION=$DEV_AWS_DEFAULT_REGION                
                - python ./import-env.py $DEV_DEPLOYMENT_ID --output=env.properties
                - mvn --version
                - mvn -X clean deploy -Dall
    master:            
      - step:
          script: # Modify the commands below to build your repository.
                - export USER_S3_BUCKET=$prod_user_s3_bucket
                - export AWS_ACCESS_KEY_ID=$PROD_AWS_ACCESS_KEY_ID
                - export AWS_SECRET_ACCESS_KEY=$PROD_AWS_SECRET_ACCESS_KEY
                - export AWS_DEFAULT_REGION=$PROD_AWS_DEFAULT_REGION                
                - python ./import-env.py $PROD_DEPLOYMENT_ID --output=env.properties
                - mvn --version
                - mvn -X clean deploy -Dall
