name = "TipoTapp Docs"
license = "TipoTapp License"
licenselink = "https://app.tipotapp.com/license"
description = TipoTapp Documentation"
homepage = "https://app.tipotapp.com"
tags = ["tipotapp", "documentation", "docs", "tutorial", "how to", "getting started guide"]
features = []
min_version = 0.20

[author]
  name = "TipoTapp"
  homepage = "https://tipotapp.com"

