baseurl = "https://dev.tipotapp.com/docs/"
languageCode = "en-us"
title = "TipoTapp Documentation"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = "UA-92686434-1"

[params]
	# General information
	author = "TipoTapp"
	description = "TipoTapp - Documentation"
	copyright = "TipoTapp Inc"

	#Repository
	provider = "TipoTapp"
	repo_url = "https://tipotapp.com"

	version = "1.0.0"
	logo = "images/logo.png"
	favicon = "images/favicon.ico"
	app = "https://dev.tipotapp.com"

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "teal"
    	accent  = "deep-orange"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = "tipotapp"
	email   = "info@tipotapp.com"

	
[[menu.main]]
	name   = "Introduction"
	url    = "introduction/"
	weight = 1

[[menu.main]]
	name   = "Quickstart"
	url    = "quickstart/"
	weight = 2
	
[[menu.main]]
	name   = "Advanced Concepts"
	url   = "advanced_concepts/"
	weight = 3
	
[[menu.main]]
	name   = "Extending Your Application"
	url    = "extending_your_application/"
	weight = 4

	
[[menu.main]]
	name   = "Creating an Application - Basic"
	url    = "creating_an_application_basic/"
	weight = 5
	
[[menu.main]]
	name   = "Creating an Application - Intermediate"
	url    = "creating_an_application_intermediate/"
	weight = 6
	
[[menu.main]]
	name   = "Creating an Application - Advanced"
	url    = "creating_an_application_advanced/"
	weight = 7
	
[[menu.main]]
	name   = "TipoTapp's Interface"
	url   = "tipotapp_interface/"
	weight = 8
	
[[menu.main]]
	name   = "Reference Manual"
	url    = "reference_manual/"
	weight = 9

[[menu.main]]
	name   = "Developer Documentation"
	url    = "developer_documentation/"
	weight = 10

[[menu.main]]
	name   = "Client Side Customisations"
	url    = "client_side_customisations/"
	weight = 11

[[menu.main]]
	name   = "Server Side Customisations"
	url    = "server_side_customisations/"
	weight = 12



