languageCode = "en-us"
title = "TipoTapp Docs"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "Digitalcraftsman"
	description = "A material design theme for documentations."
	copyright = "TipoTapp Inc"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/digitalcraftsman/hugo-material-docs"

	version = "1.0.0"
	logo = "../assets/images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "teal"
    	accent  = "red"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = ""
	github  = "digitalcraftsman"
	email   = "hello@email.com"


[[menu.main]]
	name   = "Material"
	url    = "/"
	weight = 0


[[menu.main]]
	name   = "Tipo Functions"
	url    = "tipo_functions/index.html"
	weight = 10

[[menu.main]]
	name   = "Tipo Authentication API"
	url    = "tipo_authentication_api/index.html"
	weight = 20

[[menu.main]]
	name   = "Tipo Definitions"
	url    = "tipo_definitions/index.html"
	weight = 30

[[menu.main]]
	name   = "Tipo Filters"
	url    = "tipo_filters/index.html"
	weight = 40

[[menu.main]]
	name   = "Tipo JavaScript SDK"
	url    = "tipo_javascript_sdk/index.html"
	weight = 50


[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
